package com.example.pengxuanping.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.pengxuanping.greendaodemo.StudentMsgBean;
import com.example.pengxuanping.demo11.ScoreBean;
import com.example.pengxuanping.demo11.StudentBean;

import com.example.pengxuanping.dao.StudentMsgBeanDao;
import com.example.pengxuanping.dao.ScoreBeanDao;
import com.example.pengxuanping.dao.StudentBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig studentMsgBeanDaoConfig;
    private final DaoConfig scoreBeanDaoConfig;
    private final DaoConfig studentBeanDaoConfig;

    private final StudentMsgBeanDao studentMsgBeanDao;
    private final ScoreBeanDao scoreBeanDao;
    private final StudentBeanDao studentBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        studentMsgBeanDaoConfig = daoConfigMap.get(StudentMsgBeanDao.class).clone();
        studentMsgBeanDaoConfig.initIdentityScope(type);

        scoreBeanDaoConfig = daoConfigMap.get(ScoreBeanDao.class).clone();
        scoreBeanDaoConfig.initIdentityScope(type);

        studentBeanDaoConfig = daoConfigMap.get(StudentBeanDao.class).clone();
        studentBeanDaoConfig.initIdentityScope(type);

        studentMsgBeanDao = new StudentMsgBeanDao(studentMsgBeanDaoConfig, this);
        scoreBeanDao = new ScoreBeanDao(scoreBeanDaoConfig, this);
        studentBeanDao = new StudentBeanDao(studentBeanDaoConfig, this);

        registerDao(StudentMsgBean.class, studentMsgBeanDao);
        registerDao(ScoreBean.class, scoreBeanDao);
        registerDao(StudentBean.class, studentBeanDao);
    }
    
    public void clear() {
        studentMsgBeanDaoConfig.clearIdentityScope();
        scoreBeanDaoConfig.clearIdentityScope();
        studentBeanDaoConfig.clearIdentityScope();
    }

    public StudentMsgBeanDao getStudentMsgBeanDao() {
        return studentMsgBeanDao;
    }

    public ScoreBeanDao getScoreBeanDao() {
        return scoreBeanDao;
    }

    public StudentBeanDao getStudentBeanDao() {
        return studentBeanDao;
    }

}
